name: "Must Star"
description: "Require users who open a PR to star the repo first"
inputs:
  token:
    description: "Github personal access token with PR write"
    required: true
runs:
  using: "composite"
  steps:
    - name: debug
      shell: bash
      run: |
        # print if the token is set
        if [ ! -z "${{ inputs.token }}" ]; then
          echo "gh token is not set"
        else
          echo "gh token is set"
        fi
        # done with the checking of token
        echo "GH_PAT=${{ inputs.token }}" >> $GITHUB_OUTPUT
    - name: Run the comment script
      uses: actions/github-script@v7
      with:
        github-token: "${{ env.GH_PAT}}"
        script: |
          const { script } = await import('${{ github.action_path }}/src/index.js')
          await script({ github, context });
