name: Check Stars on PRs and Issues

on:
  pull_request:
    types: [opened]
    branches:
      - "*"

  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: hacksore/must-star-action@master
        with:
          github-token: ${{ secrets.GH_PAT }}
